name: "Haskell Integration (Experimental)"

on:
  push: {}

  pull_request:
    branches:
      - master

  schedule:
    - cron: "0 8 * * *"

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        ghc:
          - "9.0.1"
    steps:
      - uses: actions/checkout@v2

      - uses: haskell/actions/setup@v1.1.5
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: "3.4.0.0"

      - uses: actions/cache@v2
        with:
          path: ~/.cabal
          key: cabal-root-${{ matrix.ghc }}

      - name: Update Hackage snapshot
        run: cabal update

      - name: Configure library
        run: cabal configure --enable-documentation --enable-tests --disable-optimization

      - name: Build dependencies
        run: cabal build --dependencies-only

      - name: Build library
        run: cabal build

      - name: Run tests
        run: cabal test
